# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('participantes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
        ),
    ]
