# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço'),
        ),
    ]
