# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0003_auto_20170825_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='descricao',
            field=models.CharField(max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
