# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0006_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_multa',
            field=models.FloatField(default=2.0, verbose_name='Valor da multa'),
        ),
    ]
