# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0007_evento_valor_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='dia_evento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='momento_da_solicitacao',
            field=models.DateTimeField(blank=True),
        ),
    ]
