# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0008_auto_20170827_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='intervalo',
            field=models.CharField(choices=[('D', 'Dias'), ('S', 'Semanas'), ('M', 'Meses')], max_length=40),
        ),
    ]
