# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0013_comentariosdeeventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='houve_atraso',
            field=models.BooleanField(default=False),
        ),
    ]
