# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='emails_nao_periodicos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='emails_periodicos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='emails_de_adicoes_em_ambientes',
            field=models.BooleanField(default=True, verbose_name='Notificações para quando te adicionam em um ambiente'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emails_de_comentarios_em_tarefas',
            field=models.BooleanField(default=True, verbose_name='Notificações comentários em tarefas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emails_de_lembrete_de_tarefas',
            field=models.BooleanField(default=True, verbose_name='Notificações para lembrete caso ainda não tenha concluído suas tarefas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emails_de_novas_multas_e_tarefas',
            field=models.BooleanField(default=True, verbose_name='Notificações para suas tarefas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emails_de_novas_multas_no_ambiente',
            field=models.BooleanField(default=True, verbose_name='Notificações de multas em ambientes'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emails_de_validações',
            field=models.BooleanField(default=True, verbose_name='Notificações de validações de tarefas'),
        ),
    ]
